spring:
  application:
    name: Athenea
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/athenea
    username: atheneadb
    password: athenea

  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  thymeleaf:
    mode: HTML
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 8898
  error:
    whitelabel:
      enabled: false
  address: 127.0.0.1

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.beogotech: INFO

